[env:m5stack-core2]
platform = espressif32
board = m5stack-core2
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = /dev/cu.usbserial-02ED1015
build_flags = 
    -DCORE_DEBUG_LEVEL=0
lib_deps =
    m5stack/M5Unified@^0.2.4
    fastled/FastLED@^3.9.0
